version: 2


config_android: &config_android
  docker:
    - image: circleci/android:api-28-alpha
  working_directory: ~/myapp
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    TERM: dumb

update_sdk: &update_sdk
  run:
    name: Update SDK
    command: |
      mkdir "$ANDROID_HOME/licenses" || true
      echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
      echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      sdkmanager "platform-tools" "platforms;android-28"

google_services_json: &google_services_json
  run:
    name: Write Google Services JSON file
    command: echo "$google_services_json" > presentation/google-services.json

jobs:
  build:
    <<: *config_android
    steps:
      - <<: *update_sdk
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "presentation/build.gradle" }}-{{ checksum "domain/build.gradle" }}-{{ checksum "data/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - <<: *google_services_json
      - run:
          name: Run Tests
          command: ./gradlew test --stacktrace
      - run:
          name: Run JaCoCo
          command: ./gradlew build jacocoFullReport "-Pargs=ci,${CIRCLE_BUILD_NUM}"
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Run Danger
          command: bundle exec danger
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "presentation/build.gradle" }}-{{ checksum "domain/build.gradle" }}-{{ checksum "data/build.gradle" }}
      - store_artifacts:
          path: app/build/outputs
          destination: outputs

